# Generated by Django 3.2.25 on 2024-03-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='instructor_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
    ]
