# Generated by Django 5.0.3 on 2024-04-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_lesson_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
