# Generated by Django 5.0.3 on 2024-04-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_userprofile_default_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
